#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls="exa --icons"
alias l="ls -l"
alias ll="ls -lah"
alias la="ls -lah"
alias lt='ls --tree'
alias lg='ls -lah --grid'

alias e="emacsclient"
alias ec="emacsclient -c"
alias enw="emacsclient -nw"
alias vi=nvim

alias cat="bat --theme='zenburn'"

function tldr() {
    command tldr $1 | bat -p
}

function cdroot() {
    cd $(git root)
}

function git-ignore () {
    curl -L -s "https://www.gitignore.io/api/$*";
}


if [[ $UNIX_TYPE = "Darwin" ]]; then
    export XDG_CACHE_HOME="$HOME/Library/Caches/org.freedesktop"
    mkdir -p "${XDG_CACHE_HOME}"
fi

eval "$(direnv hook zsh)"

bindkey "^d" fzy-cd-widget
bindkey "^f" fzy-file-widget
bindkey "^p" fzy-proc-widget
bindkey "^r" fzy-history-widget

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

