#!/bin/zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls="exa --icons"
alias l="ls -l"
alias ll="ls -lah"
alias la="ls -lah"
alias lt='ls --tree'
alias lg='ls -lah --grid'

alias e="emacsclient"
alias ec="emacsclient -c"
alias enw="emacsclient -nw"
alias vi=nvim

alias cat="bat --theme='zenburn'"

alias gst="git status"

alias ytop="ytop -p"

alias gpg=gpg2

function tldr() {
    command tldr "$1" | bat -p
}

function cdroot() {
    cd $(git root)
}

function git-ignore () {
    curl -L -s "https://www.gitignore.io/api/$*";
}

if [[ $UNIX_TYPE = "Darwin" ]]; then
    export XDG_CACHE_HOME="$HOME/Library/Caches/org.freedesktop"
    mkdir -p "${XDG_CACHE_HOME}"
fi

# GPG Agent
if [ -f "${HOME}/.gpg-agent-info" ]; then
  . "${HOME}/.gpg-agent-info"
  export GPG_AGENT_INFO
  export SSH_AUTH_SOCK
  export SSH_AGENT_PID
fi

GPG_TTY=$(tty)
export GPG_TTY



# Direnv
eval "$(direnv hook zsh)"

# fzf keybindings
if [[ $HOST = "ShaneMBP.local" ]]; then
    fzf_bindings_path=/opt/local/share/fzf/shell
elif [[ $HOST = "smsegal-pc" ]]; then
    fzf_bindings_path=/usr/share/fzf
elif [[ "$(lsb_release -sc)" == "void" ]]; then
    fzf_bindings_path=/usr/share/doc/fzf
else
    fzf_bindings_path=/usr/share/fzf/shell
fi
source $fzf_bindings_path/key-bindings.zsh

# Nix Package Manager
if [ -x $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
    source $HOME/.nix-profile/etc/profile.d/nix.sh
fi

# Pyenv setup

# lazy load
# Check if 'pyenv' is a command in $PATH
if [ $commands[pyenv] ]; then
  source '/home/shane/.pyenv/libexec/../completions/pyenv.zsh'
  # Placeholder 'pyenv' shell function:
  # Will only be executed on the first call to 'pyenv'
  pyenv() {
    # Remove this function, subsequent calls will execute 'pyenv' directly
    unfunction "$0"

    export PATH="/home/shane/.pyenv/shims:${PATH}"
    export PYENV_SHELL=zsh
    command pyenv rehash 2>/dev/null
    pyenv() {
        local command
        command="${1:-}"
        if [ "$#" -gt 0 ]; then
            shift
        fi

        case "$command" in
        rehash|shell)
            eval "$(pyenv "sh-$command" "$@")";;
        *)
            command pyenv "$command" "$@";;
        esac
    }

    # Execute 'kubectl' binary
    $0 "$@"
  }
fi


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
